registry:
  restart: always
  image: registry:2
  ports:
    - 0.0.0.0:5000:5000
  expose:
    - 5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - ./data:/data    
  volumes:
    - "./docker-images:/data"
# a unica referencia que funcionou decentemente
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04
# Lista de configuracoes possiveis
# https://docs.docker.com/registry/configuration/#list-of-configuration-options
# Tutorial pra montar um repositorio local
# https://docs.docker.com/registry/deploying/#run-a-local-registryl
