version: "2"
services:
  ftp:
    image: 192.168.0.18:5000/ftp_server
#    image: ftp_server
    ports:
      - "9020:9020"
      - "9021:21"
      - "9022:22"
      - "21800-21930:21800-21930"
    volumes:
      - ./ftp:/var/ftp
      - ./empty:/var/run/vsftpd/empty
